### ISSUE TITLE
S3 APIs throw error on Julia v0.4

### ISSUE THREAD

**Issue by tanmaykm** [amitmurthy/AWS.jl#40]
S3 bucket listing fails on Julia v0.4:

````
List all buckets
ERROR: LoadError: Associative collections only contain Pairs;
Either look for e.g. A=>B instead, or use the `keys` or `values`
function if you are looking for a key or value respectively.
 in in at dict.jl:13
 in get_canon_amz_headers at /home/tanmaykm/.julia/v0.4/AWS/src/S3.jl:777
 in canonicalize_and_sign at /home/tanmaykm/.julia/v0.4/AWS/src/S3.jl:683
 in do_http at /home/tanmaykm/.julia/v0.4/AWS/src/S3.jl:612
 in __do_request#664__ at no file
 [inlined code] from /home/tanmaykm/.julia/v0.4/AWS/src/S3.jl:17
 in list_all_buckets at /home/tanmaykm/.julia/v0.4/AWS/src/S3.jl:71
 in include at ./boot.jl:260
 in include_from_node1 at ./loading.jl:271
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/tanmaykm/.julia/v0.4/AWS/test/tests3.jl, in expression starting on line 9
````

**Comment by josefsachsconning** [comment]
In https://github.com/Conning/AWS.jl/commit/c6a3cfc7522314da9f9cd25e9288d181c5c2c82c I work around the problem by turning the array of pairs into an array of tuples in get_canon_amz_headers() in S3.jl, perhaps not the most elegant solution.

**Comment by tanmaykm** [comment]
Thanks @josefsachsconning.

Yes, that does seem to handle this case. I was about to introduce using Compat.jl, but it may be better to do that across all sources separately.

I see that you have also fixed a few other warnings in your branch. Would you be able to submit a PR?

Also AWS.jl needs to be tagged with the latest commits.

**Comment by amitmurthy** [comment]
I think this is fixed now. Please reopen if not.
