### ISSUE TITLE
S3.get_bkt(...) gives missing method error -- possible LibExpat issue

### ISSUE THREAD

**Issue by JohnHBrock** [amitmurthy/AWS.jl#42]
Not sure if this is a problem with AWS.jl or LibExpat.jl: pinning to version v0.0.8 of LibExpat.jl makes the error go away.

```julia
julia> opt = S3.GetBucketOptions(prefix=_prefix, marker=""); resp = S3.get_bkt(env, bkt, options=opt)
ERROR: `find` has no method matching find(::ETree, ::ASCIIString)
in ListBucketResult at /home/user/.julia/v0.3/AWS/src/s3_types.jl:206
in get_bkt at /home/user/.julia/v0.3/AWS/src/S3.jl:22
```

versioninfo():
```
Julia Version 0.3.8-pre+22
Commit 5078421* (2015-04-28 09:05 UTC)
Platform Info:
  System: Linux (x86_64-amazon-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libmkl_rt
  LAPACK: libmkl_rt
  LIBM: libimf
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
can you try qualifying `find` as `LibExpat.find`, ref #45?

**Comment by JohnHBrock** [comment]
I'm getting the same error even after I make that change.

**Comment by amitmurthy** [comment]
Since you are on Julia 0.3, we will need to pin https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/AWS/versions/0.1.8/requires to a specific version of LibExpat.

**Comment by JohnHBrock** [comment]
The update to METADATA fixed the problem without needing to pin to a specific version, thanks!
